# Generated by Django 3.0 on 2019-12-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='age1',
            field=models.IntegerField(default=1),
        ),
    ]
