# Generated by Django 3.0 on 2019-12-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_age2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='age',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='age1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='age2',
        ),
    ]
